// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm6S7Qwqgrqw_E77U6wisQMb3jGzrVZC8',
    appId: '1:123623304435:web:080100e0e75cfbb729db86',
    messagingSenderId: '123623304435',
    projectId: 'flutterfirebasecrud-dfa52',
    authDomain: 'flutterfirebasecrud-dfa52.firebaseapp.com',
    storageBucket: 'flutterfirebasecrud-dfa52.appspot.com',
    measurementId: 'G-9GVPZQZ958',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhPbQp8K9Ja-XTSyI9pBZPF5YtUofMqTU',
    appId: '1:123623304435:android:8ac893d9f8d0049d29db86',
    messagingSenderId: '123623304435',
    projectId: 'flutterfirebasecrud-dfa52',
    storageBucket: 'flutterfirebasecrud-dfa52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOELZO6UH5AidqCeT-ReXI1-FYt3SGA5Q',
    appId: '1:123623304435:ios:3b5e1c053ae5b3e829db86',
    messagingSenderId: '123623304435',
    projectId: 'flutterfirebasecrud-dfa52',
    storageBucket: 'flutterfirebasecrud-dfa52.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOELZO6UH5AidqCeT-ReXI1-FYt3SGA5Q',
    appId: '1:123623304435:ios:3b5e1c053ae5b3e829db86',
    messagingSenderId: '123623304435',
    projectId: 'flutterfirebasecrud-dfa52',
    storageBucket: 'flutterfirebasecrud-dfa52.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm6S7Qwqgrqw_E77U6wisQMb3jGzrVZC8',
    appId: '1:123623304435:web:7a7336b9a24646f229db86',
    messagingSenderId: '123623304435',
    projectId: 'flutterfirebasecrud-dfa52',
    authDomain: 'flutterfirebasecrud-dfa52.firebaseapp.com',
    storageBucket: 'flutterfirebasecrud-dfa52.appspot.com',
    measurementId: 'G-XEK2SGCWQQ',
  );
}
